# Generated by Django 4.1.7 on 2023-03-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=300)),
                ('image_alt', models.CharField(max_length=200)),
                ('alt_approved', models.BooleanField(default=False)),
                ('favorites_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('dairy_free', models.BooleanField()),
                ('incl_choc_cover', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
