# Generated by Django 4.1.7 on 2023-03-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='incl_choc_cover',
            field=models.BooleanField(default=True),
        ),
    ]
